name: Convert Jupyter Notebooks to Python Scripts

on:
  push:
    paths:
      - '**.ipynb'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install nbconvert
      run: pip install nbconvert
    - name: Convert Notebooks
      run: |
        jupyter nbconvert --to script ../portfolio/census_Poverty/1_data_Acquisition.ipynb
        jupyter nbconvert --to script ../portfolio/census_Poverty/2_data_Pre_Processing.ipynb
        jupyter nbconvert --to script ../portfolio/census_Poverty/3_data_Visualization_and_Exploration.ipynb
